version: '2'

services:
  webui:
    image: thermostat/webui-dev
    volumes:
      - ../webui:/opt/thermostat/webui
      - .:/opt/thermostat/docker-dev
    ports:
      - 4201:4201

  broker:
    image: eclipse-mosquitto
    volumes:
      - ./broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
      - 9001:9001

  daemon:
    environment:
      - TZ
    depends_on:
      - broker
    image: thermostat/daemon-dev
    volumes:
      - ../daemon:/opt/thermostat/daemon
      - .:/opt/thermostat/docker-dev
    ports:
      - 7475:7475

  webserver:
    depends_on:
      - daemon
      - broker
      - webui
    image: nginx
    volumes:
      - ./webserver/nginx-default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:8080
